---
title: "Effects of diversity, topography, and interannual climate variability on pathogen spillover"
author: "Whalen Dillon"
date: "February 25, 2016"
output: html_document
---

## Background/Question/Methods
Variation in disease transmission is caused by heterogeneity of individuals, species, and landscapes across space and time. For example, multi-host disease systems are often characterized by pathogen spillover due to differences between host-pathogen interactions among the various hosts. Understanding the complexities of these disease dynamics at meaningful scales is a continuing challenge for disease ecologists. Sudden oak death is a multi-host forest disease characterized by pathogen spillover, where a single host species (California bay laurel) amplifies the pathogen, which spills over to infect nearby oak trees. We used path analysis to analyze the direct and indirect effects of diversity, topography, and interannual climate variability on pathogen spillover (oak infection). The hypothesized relationships laid out by our path model for sudden oak death were based on published findings from experiments and observations of the disease during the past 15 years. We applied our path analysis framework to 10 years of data from a network of disease-monitoring plots distributed across a 275-km2 area in southeastern Sonoma County, California. During each year, we measured temperature, rainfall, pathogen load, and oak infection, while plant community diversity was measured once at each plot in this low-turnover landscape.


## Results/Conclusions
We assessed our initial path model using measurements summarized for each plot. Our analysis indicated that diversity reduced pathogen spillover through a relatively strong direct negative effect on oak infection, however, this was tempered by more diverse plots also having a higher pathogen load. Pathogen load had the strongest direct positive effect on oak infection, which was countered by direct negative influences from temperature, and interestingly, bay laurel density. Our temperature variable was calcuated as the averaged daily maximum temperature during June-September preceding the spring sampling season, a time when bay laurel will drop damaged leaves. Our hypothesis was that higher temperatures leads to more leaf abscision and fewer infections persisting until the wet season. We tested the number of rainy days during November-May for each sampling season as our initial rainfall variable, because persistent moisture is more favorable for pathogen reproduction. However, this had a relatively weak effect on pathogen load. So far, we have confirmed a dilution effect via diversity reducing likelihood of oak infection, pathogen load has the single greatest effect on pathogen spillover, and discovered a surprising relationship between bay laurel and oak infection warranting further exploration.

